### ISSUE TITLE
Not able to connect the images folder to tensorflow on Windows

### ISSUE THREAD

**Issue by anujdutt9** [bit-please/Star-wars-classifier#1]
Hi. I tried your method of connecting the images folder to tensorflow.
It gets connected but then there are no images in that. It has the folder flower_photos on tensorflow but when I run the git pull and next commands, it says no images found.
The folder is in my current working directory. So I am connecting it using command:
"docker run -it -v /tf_files/flower_photos  gcr.io/tensorflow/tensorflow:latest-devel"
I even tried using "/tf_files:/tf_files/" but didn't worked.
Can you please help.
Thanks :)

**Comment by hiteshvaidya** [comment]
Hi,

How did you download the image dataset? If you have used fatkun batch image
downloader (as shown in sirajology video) then you need to move all the
images to that folder. You can use 'mv' bash command or you can use
cut+paste. If you are downloading dataset from google using bash commands
like shown on tensorflow tutorial then you have to follow the steps
mentioned there (because I didn't use that method, I used method shown by
siraj).

Tensorflow tutorial -
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/?utm_campaign=chrome_series_machinelearning_063016&utm_source=gdev&utm_medium=yt-desc#3

Regards,
Hitesh Vaidya
M: +91-8652848287

**Comment by mayur10** [comment]
I did try the method as given in siraj youtube video but i am unable to move the images into the docker container.
can u please help..??
Thanks..!!

**Comment by hiteshvaidya** [comment]
You can use terminal commands like mv or you could move them normally like
you move any other file in your computer

**Comment by mayur10** [comment]
how can i move physically..?? where is the container located so that i can copy paste it..??
I have photos on the desktop, can u tell me the mv command to move the files in my container from my desktop.??

**Comment by hiteshvaidya** [comment]
`mv <source_file_address/source_file_name> <target_folder_path>`

**Comment by paulsonpaul312** [comment]
try "docker run -it -v ~/tf_files/flower_photos gcr.io/tensorflow/tensorflow:latest-devel" , the '~' stands for home directory in docker

**Comment by paulsonpaul312** [comment]
`docker run -it -v ~/tf_files/flower_photos gcr.io/tensorflow/tensorflow:latest-devel`  , try the ~ in front of the path, ~ stands for home directory

**Comment by shahidgeek** [comment]
https://colab.research.google.com/drive/1hFte7dNUZGVukuR0OY02t0atJgMzn6oc#scrollTo=Bl-yFZqKeezp&forceEdit=true&offline=true&sandboxMode=true


**Step 0** 

Replace retrain.py with downloading file from following link and uploading it to same folder in Google drive.

https://raw.githubusercontent.com/tensorflow/hub/master/examples/image_retraining/retrain.py


**Step 1**

Go to this link : 

https://colab.research.google.com/drive/1hFte7dNUZGVukuR0OY02t0atJgMzn6oc#scrollTo=Bl-yFZqKeezp&forceEdit=true&offline=true&sandboxMode=true

**Step 2**

Go to chapter Two

**Step 3** 

**Worked by adding two lines as given following before the script section : LOL**

**It's a LOL that just added following two lines and it worked before script section and it worked.**

**Two Lines:**


    if not os.path.isdir("../Pokemons-subset"):
  
         print('Error')


**Script Section:**


     %run scripts/retrainn.py   \

       --bottleneck_dir=tf_files/bottlenecks   \

       --how_many_training_steps=4000   \

       --model_dir=tf_files/models/   \

       --summaries_dir=tf_files/training_summaries/mobilenet_0.50_160   \

       --output_graph=tf_files/retrained_graph.pb   \

       --output_labels=tf_files/retrained_labels.txt   \

       --learning_rate=0.01   \

       --architecture=mobilenet_0.50_160   \

       --image_dir=../Pokemons-subset \

       --flip_left_right \

       --random_crop=10 \

       --random_scale=10 \

       --random_brightness=10
