### ISSUE TITLE
please help !!

### ISSUE THREAD

**Issue by stormcch** [bit-please/Star-wars-classifier#2]
hello guys
sorry for noob question
but i need help

i stuck at part 6 !! 
after run docker run -it -v $HOME/tf_files:/xxxx
root@xxxx :-# 
so i continue with cd /tensorflow 
-> git pull 
-> root@xxxx :/tensorflow# 

**part 6** 
-> python tensorflow/examples/image_retraining/retrain.py \
--bottleneck_dir=/tf_files/bottlenecks \
--how_many_training_steps 500 \
--model_dir=/tf_files/inception \
--output_graph=/tf_files/retrained_graph.pb \
--output_labels=/tf_files/retrained_labels.txt \
--image_dir /tf_files/animal_la

**>> Downloading inception-2015-12-05.tgz 100.0%
Successfully downloaded inception-2015-12-05.tgz 88931400 bytes.
Looking for images in 'tools'
No files found
Looking for images in 'tensorflow'
No files found
Looking for images in 'tools'
No files found
Looking for images in 'git'**

what should i do ?? i already redo and same problem where do i do wrong ??
thanks

**Comment by quantamc** [comment]
You sure there are picture folders in anima_la?

**Comment by stormcch** [comment]
thanks for reply bro

already fix it ......



________________________________
