### ISSUE TITLE
How to test the classifier with a new image which I want to classify and is stored in home directory . I am using Ubuntu 16.04 with docker . 

### ISSUE THREAD

**Issue by mayur10** [bit-please/Star-wars-classifier#3]
Whenever I try to link the tf_files folder a new container is created so i linked the images and the label_image.py with tensorflow . Now I have picture which I downloaded from internet and want to test it with my classifier . how can I test this image .?? I used the command 
python /tf_files/label_image.py $HOME/1.jpg 
It is giving me and error that home/1.jpg not found .
What should I do ????

**Comment by hiteshvaidya** [comment]
Hi @mayur10,
My apologise for replying so late. Did you try the program in the later part of siraj raval's video? I think that procedure must help. I had followed the same procedure to recognise new images.
Hope that helps.
